"""align model indexes and constraints

Revision ID: a77e176f0679
Revises: 0006_leads_contact_required
Create Date: 2026-08-23 20:12:20.206382

"""
from alembic import op
import sqlalchemy as sa


revision = 'a77e176f0679'
down_revision = '0006_leads_contact_required'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discovery_opportunities_property_id_key', 'discovery_opportunities', type_='unique')
    op.drop_index('ix_opportunity_latest_observation_id', table_name='discovery_opportunities')
    op.drop_index('ix_opportunity_property_id', table_name='discovery_opportunities')
    op.drop_index('ix_opportunity_reviewed_by', table_name='discovery_opportunities')
    op.create_index(op.f('ix_discovery_opportunities_latest_observation_id'), 'discovery_opportunities', ['latest_observation_id'], unique=False)
    op.create_index(op.f('ix_discovery_opportunities_property_id'), 'discovery_opportunities', ['property_id'], unique=True)
    op.create_index(op.f('ix_discovery_opportunities_reviewed_by'), 'discovery_opportunities', ['reviewed_by'], unique=False)
    op.drop_index('ix_observation_canonical_url', table_name='listing_observations')
    op.drop_index('ix_observation_property_id', table_name='listing_observations')
    op.drop_index('ix_observation_source_id', table_name='listing_observations')
    op.drop_index('ix_observation_source_listing_id', table_name='listing_observations')
    op.create_index(op.f('ix_listing_observations_canonical_url'), 'listing_observations', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_listing_observations_property_id'), 'listing_observations', ['property_id'], unique=False)
    op.create_index(op.f('ix_listing_observations_source_id'), 'listing_observations', ['source_id'], unique=False)
    op.create_index(op.f('ix_listing_observations_source_listing_id'), 'listing_observations', ['source_listing_id'], unique=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_listing_observations_source_listing_id'), table_name='listing_observations')
    op.drop_index(op.f('ix_listing_observations_source_id'), table_name='listing_observations')
    op.drop_index(op.f('ix_listing_observations_property_id'), table_name='listing_observations')
    op.drop_index(op.f('ix_listing_observations_canonical_url'), table_name='listing_observations')
    op.create_index('ix_observation_source_listing_id', 'listing_observations', ['source_listing_id'], unique=False)
    op.create_index('ix_observation_source_id', 'listing_observations', ['source_id'], unique=False)
    op.create_index('ix_observation_property_id', 'listing_observations', ['property_id'], unique=False)
    op.create_index('ix_observation_canonical_url', 'listing_observations', ['canonical_url'], unique=False)
    op.drop_index(op.f('ix_discovery_opportunities_reviewed_by'), table_name='discovery_opportunities')
    op.drop_index(op.f('ix_discovery_opportunities_property_id'), table_name='discovery_opportunities')
    op.drop_index(op.f('ix_discovery_opportunities_latest_observation_id'), table_name='discovery_opportunities')
    op.create_index('ix_opportunity_reviewed_by', 'discovery_opportunities', ['reviewed_by'], unique=False)
    op.create_index('ix_opportunity_property_id', 'discovery_opportunities', ['property_id'], unique=False)
    op.create_index('ix_opportunity_latest_observation_id', 'discovery_opportunities', ['latest_observation_id'], unique=False)
    op.create_unique_constraint('discovery_opportunities_property_id_key', 'discovery_opportunities', ['property_id'])
    # ### end Alembic commands ###
